### ISSUE TITLE
Add GitPod support

### ISSUE THREAD

**Issue by dannysmith** [dannysmith/jimmy#410]
This allows an entire rails environment and editor to be spun up in the cloud so folks can work on it anywhere via gitpod.io. 

Here's an example `.gitpod.yml` file for a rails project.

```yaml
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true
```

Here's an example for freeCodeCamp: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/.gitpod.yml
